### ISSUE TITLE
Error after update packt.

### ISSUE THREAD

**Issue by almir-lima** [jmpessoa/lazandroidmodulewizard#254]
After update packt an error occurs.
i tried reinstall but a error persists.
i needed update because the function, "Update Table" don't it was working
 
![Capturar](https://user-images.githubusercontent.com/58075693/93004238-9b7ffd80-f51b-11ea-8d40-f0265d0a32be.PNG)

**Comment by jmpessoa** [comment]
Maybe the file "Controls.java"   is missing in
folder  "....\android_wizard\smartdesigner\java"

**Comment by almir-lima** [comment]
I managed to install but any new project the error happen:
![Capturar_](https://user-images.githubusercontent.com/58075693/93004900-f0267700-f521-11ea-8c1e-e4d4642bc55d.PNG)

**Comment by jmpessoa** [comment]
Ok. Now I can try fix this bug.... just wait a moment....

**Comment by jmpessoa** [comment]
Fixed!!!

Thank you!

**Comment by almir-lima** [comment]
Hi, i deleted the folder LAWM and clone the same, but error perssists.
I deleted the folder "VendaFacil\src\org\lamw\vendafacil".
The LAWM rebuild the folder and the java components, but error persists yet.
![Capturar](https://user-images.githubusercontent.com/58075693/93088443-45709e80-f670-11ea-96e3-e088eb2ffb9c.PNG)

**Comment by jmpessoa** [comment]
So, you need keep target 28!!
(this is a google play requirement!)

I will try to fix the "jHttpClient.java" at line 1239...  (can you comment this line?)

**Comment by jmpessoa** [comment]
"jHttpClient.java" Fixed!

Thank you!

**Comment by almir-lima** [comment]
Its worked.
I used SDK 26 to maintenance the compatibility with Android 6.

Thank for all.
